[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = ["src"]

[project]
dependencies = ["numpy", "matplotlib", "pandas"]
name = "icorr"
dynamic = ["version"]

[tool.mypy]
python_version = "3.x"
mypy_path = "src"
